CREATE TABLE IF NOT EXISTS recipients (
    id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('male', 'female', 'other') NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    address TEXT NOT NULL,
    medical_condition TEXT NOT NULL,
    blood_type VARCHAR(5) NOT NULL,
    organ_required VARCHAR(50) NOT NULL,
    medical_records_path TEXT NOT NULL,
    id_type VARCHAR(50) NOT NULL,
    id_proof_path VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    policy_agreement BOOLEAN NOT NULL DEFAULT FALSE,
    medical_records_consent BOOLEAN NOT NULL DEFAULT FALSE,
    terms_agreement BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified BOOLEAN DEFAULT FALSE,
    odm_id VARCHAR(50) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status ENUM('active', 'inactive', 'withdrawn') DEFAULT 'active'
);
